# Generated by Django 2.0.1 on 2018-03-05 17:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress1', models.CharField(max_length=200)),
                ('adress2', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('activation_key', models.CharField(default='1234', max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.datetime(2045, 7, 20, 17, 59, 22, 292037, tzinfo=utc))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SMS.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
