# Generated by Django 2.0.1 on 2018-03-05 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 20, 22, 6, 27, 532464, tzinfo=utc)),
        ),
    ]
