# Generated by Django 2.0.1 on 2018-03-06 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_auto_20180306_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='DUNS',
            field=models.CharField(default='111111111', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 21, 3, 5, 1, 239697, tzinfo=utc)),
        ),
    ]
