# Generated by Django 2.0.1 on 2018-03-06 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0006_auto_20180306_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='DUNS',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 21, 3, 11, 50, 514705, tzinfo=utc)),
        ),
    ]
