# Generated by Django 2.0.1 on 2018-03-10 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0007_auto_20180306_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 25, 13, 3, 46, 926562, tzinfo=utc)),
        ),
    ]
