# Generated by Django 2.0.1 on 2018-03-11 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0009_auto_20180310_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='town',
            field=models.CharField(default='sample town', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 26, 1, 25, 52, 201364, tzinfo=utc)),
        ),
    ]
