# Generated by Django 2.0.1 on 2018-03-11 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0011_auto_20180311_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_number',
            field=models.IntegerField(default=99999999999, unique=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='part_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 26, 4, 49, 15, 162946, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='claim',
            name='classification',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='SMS.ClaimClassification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='SMS.ClaimStatus'),
            preserve_default=False,
        ),
    ]
