# Generated by Django 2.0.1 on 2018-03-11 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0013_auto_20180311_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 26, 5, 28, 33, 619915, tzinfo=utc)),
        ),
    ]
