# Generated by Django 2.0.1 on 2018-03-11 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0014_auto_20180311_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.ClaimClassification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 26, 5, 29, 58, 835858, tzinfo=utc)),
        ),
    ]
