# Generated by Django 2.0.1 on 2018-03-11 06:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0015_auto_20180311_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='RMA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SMS.ClaimStatus'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 26, 6, 9, 54, 993019, tzinfo=utc)),
        ),
    ]
