# Generated by Django 2.0.1 on 2018-03-14 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0016_auto_20180311_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 7, 29, 19, 11, 35, 900416, tzinfo=utc)),
        ),
    ]
