# Generated by Django 2.0.1 on 2018-03-22 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0017_auto_20180314_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 6, 0, 27, 50, 26811, tzinfo=utc)),
        ),
    ]
