# Generated by Django 2.0.1 on 2018-03-22 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0018_auto_20180322_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 6, 2, 21, 38, 974939, tzinfo=utc)),
        ),
    ]
