# Generated by Django 2.0.1 on 2018-03-26 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0022_auto_20180324_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='updated_by',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 10, 12, 41, 34, 676765, tzinfo=utc)),
        ),
    ]
