# Generated by Django 2.0.1 on 2018-03-26 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0024_auto_20180326_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 10, 15, 42, 40, 309, tzinfo=utc)),
        ),
    ]
