# Generated by Django 2.0.1 on 2018-03-26 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0025_auto_20180326_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 10, 23, 59, 44, 421233, tzinfo=utc)),
        ),
    ]
