# Generated by Django 2.0.1 on 2018-04-03 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0026_auto_20180327_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='NOK_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='OK_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 18, 9, 11, 26, 699784, tzinfo=utc)),
        ),
    ]
