# Generated by Django 2.0.1 on 2018-04-03 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0027_auto_20180403_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='description',
            new_name='D2_description',
        ),
        migrations.AddField(
            model_name='claim',
            name='responsible_in_plant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='speaking_name',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 18, 14, 55, 34, 437831, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='claim',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Plant'),
        ),
    ]
