# Generated by Django 2.0.1 on 2018-04-03 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0028_auto_20180403_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='car_maker',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='reoccurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_characteristic_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 18, 19, 40, 56, 481078, tzinfo=utc)),
        ),
    ]
