# Generated by Django 2.0.1 on 2018-04-13 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0030_auto_20180413_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d1d3',
            old_name='refuse',
            new_name='refused',
        ),
        migrations.AddField(
            model_name='d1d3',
            name='production_date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 28, 16, 3, 58, 870793, tzinfo=utc)),
        ),
    ]
