# Generated by Django 2.0.1 on 2018-04-13 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0032_auto_20180413_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 28, 20, 40, 48, 207797, tzinfo=utc)),
        ),
    ]
