# Generated by Django 2.0.1 on 2018-04-13 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0033_auto_20180413_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='d1d3',
            name='function',
            field=models.CharField(default='function', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d1d3',
            name='mail',
            field=models.EmailField(default='mailadress', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 28, 20, 41, 0, 887056, tzinfo=utc)),
        ),
    ]
