# Generated by Django 2.0.1 on 2018-04-14 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0035_auto_20180414_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='claim_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('refused', models.BooleanField(default=False)),
                ('production_date', models.DateTimeField()),
                ('production_date_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 29, 8, 48, 55, 806506, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='claim_data',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
