# Generated by Django 2.0.1 on 2018-04-14 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0037_auto_20180414_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='production_date',
            new_name='production_date_1',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 29, 11, 43, 28, 224256, tzinfo=utc)),
        ),
    ]
