# Generated by Django 2.0.1 on 2018-04-14 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0038_auto_20180414_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 29, 13, 35, 17, 645087, tzinfo=utc)),
        ),
    ]
