# Generated by Django 2.0.1 on 2018-04-14 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0040_auto_20180415_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='production_date_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 29, 23, 28, 35, 649373, tzinfo=utc)),
        ),
    ]
