# Generated by Django 2.0.1 on 2018-04-15 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0041_auto_20180415_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teammember_1',
            field=models.CharField(blank=True, help_text="Only required if 'teammember 1' is selected.", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 30, 1, 49, 58, 306161, tzinfo=utc)),
        ),
    ]
