# Generated by Django 2.0.1 on 2018-04-15 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0042_auto_20180415_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 30, 3, 11, 23, 320993, tzinfo=utc)),
        ),
    ]
