# Generated by Django 2.0.1 on 2018-04-15 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0043_auto_20180415_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='D2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('claim', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='teammember_1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 30, 7, 35, 41, 479662, tzinfo=utc)),
        ),
    ]
