# Generated by Django 2.0.1 on 2018-04-15 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0044_auto_20180415_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='D2_CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_happened', models.CharField(max_length=50)),
                ('why_problem', models.CharField(max_length=50)),
                ('when_detected', models.CharField(max_length=50)),
                ('who_detected', models.CharField(max_length=50)),
                ('where_detected', models.CharField(max_length=50)),
                ('how_detected', models.CharField(max_length=50)),
                ('how_many_NOK', models.CharField(max_length=50)),
                ('claim', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim')),
            ],
        ),
        migrations.CreateModel(
            name='D2_SV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_happened', models.CharField(max_length=50)),
                ('why_problem', models.CharField(max_length=50)),
                ('when_detected', models.CharField(max_length=50)),
                ('who_detected', models.CharField(max_length=50)),
                ('where_detected', models.CharField(max_length=50)),
                ('how_detected', models.CharField(max_length=50)),
                ('how_many_NOK', models.CharField(max_length=50)),
                ('claim', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim')),
            ],
        ),
        migrations.RemoveField(
            model_name='d2',
            name='claim',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 30, 11, 34, 18, 159694, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='D2',
        ),
    ]
