# Generated by Django 2.0.1 on 2018-04-15 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0045_auto_20180415_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d2_sv',
            old_name='how_detected',
            new_name='difference',
        ),
        migrations.RenameField(
            model_name='d2_sv',
            old_name='how_many_NOK',
            new_name='other_application',
        ),
        migrations.RenameField(
            model_name='d2_sv',
            old_name='what_happened',
            new_name='reinjecting',
        ),
        migrations.RenameField(
            model_name='d2_sv',
            old_name='when_detected',
            new_name='similar_problem',
        ),
        migrations.RenameField(
            model_name='d2_sv',
            old_name='where_detected',
            new_name='standard_process',
        ),
        migrations.RenameField(
            model_name='d2_sv',
            old_name='who_detected',
            new_name='when_produced',
        ),
        migrations.RenameField(
            model_name='d2_sv',
            old_name='why_problem',
            new_name='who_produced',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2045, 8, 30, 16, 42, 45, 240387, tzinfo=utc)),
        ),
    ]
