# Generated by Django 2.0.1 on 2018-04-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0046_auto_20180415_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='key_expires',
        ),
    ]
