# Generated by Django 2.0.1 on 2018-04-26 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0049_auto_20180426_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 11, 34, 24, 558961)),
        ),
    ]
