# Generated by Django 2.0.1 on 2018-04-27 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0052_auto_20180426_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='D3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_ongoing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 51, 11, 9706)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 51, 11, 9743)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 51, 11, 9762)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 51, 11, 9780)),
        ),
        migrations.AddField(
            model_name='d3',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
