# Generated by Django 2.0.1 on 2018-04-27 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0053_auto_20180427_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 15, 16, 58, 240023)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 15, 16, 58, 240045)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 15, 16, 58, 240060)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 15, 16, 58, 240075)),
        ),
        migrations.AlterField(
            model_name='d3',
            name='actions_ongoing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
