# Generated by Django 2.0.1 on 2018-05-04 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0056_auto_20180504_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3',
            name='FC_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_NOK_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_date_range',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='range prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_sorting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 10, 5, 51, 106757)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 10, 5, 51, 106780)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 10, 5, 51, 106795)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 10, 5, 51, 106810)),
        ),
    ]
