# Generated by Django 2.0.1 on 2018-05-07 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0057_auto_20180504_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3',
            name='FC_date_range',
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_date_from',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_date_to',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_NOK_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_date_from',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_date_to',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_necessary',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='FC_transit_sorting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_NOK_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_date_from',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_date_to',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_necessary',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_sorting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_NOK_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_date_from',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_date_to',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_necessary',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='NMB_transit_sorting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_NOK_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_date_from',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_date_to',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_necessary',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='sub_supplier_sorting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_NOK_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_date_from',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_date_to',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_necessary',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='supplier_sorting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AddField(
            model_name='d3',
            name='total_NMB_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='total_NMB_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AddField(
            model_name='d3',
            name='total_supplier_NOK',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AddField(
            model_name='d3',
            name='total_supplier_qty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 9, 24, 729815)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 9, 24, 729838)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 9, 24, 729853)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 9, 24, 729867)),
        ),
    ]
