# Generated by Django 2.0.1 on 2018-05-07 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0061_auto_20180507_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 39, 33, 545716)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 39, 33, 545737)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 39, 33, 545752)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 39, 33, 545766)),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_NOK',
            field=models.IntegerField(blank=True, max_length=25, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_qty',
            field=models.IntegerField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_qty',
            field=models.IntegerField(blank=True, max_length=25, null=True, verbose_name='Qty sorted'),
        ),
    ]
