# Generated by Django 2.0.1 on 2018-05-07 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0062_auto_20180507_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 44, 28, 330998)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 44, 28, 331019)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 44, 28, 331034)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 9, 44, 28, 331048)),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_NOK',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_NOK',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_NOK',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_NOK',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_NOK',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty sorted'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_NOK',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nb NOK found'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty sorted'),
        ),
    ]
