# Generated by Django 2.0.1 on 2018-05-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0064_auto_20180507_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3',
            name='total_NMB_NOK',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='total_NMB_qty',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='total_supplier_NOK',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='total_supplier_qty',
        ),
        migrations.AddField(
            model_name='d3',
            name='LL',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 13, 31, 39, 143955)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 13, 31, 39, 143977)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 13, 31, 39, 143993)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 13, 31, 39, 144008)),
        ),
    ]
