# Generated by Django 2.0.1 on 2018-05-07 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0065_auto_20180507_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3',
            name='fst_OK_parts_del_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivery date NMB'),
        ),
        migrations.AddField(
            model_name='d3',
            name='fst_OK_parts_del_note',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='delivery note Nb'),
        ),
        migrations.AddField(
            model_name='d3',
            name='fst_OK_parts_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty'),
        ),
        migrations.AddField(
            model_name='d3',
            name='mark_on_labels',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='on labels'),
        ),
        migrations.AddField(
            model_name='d3',
            name='mark_on_parts',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='on parts'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 14, 29, 45, 773403)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 14, 29, 45, 773424)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 14, 29, 45, 773439)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 14, 29, 45, 773453)),
        ),
        migrations.AlterField(
            model_name='d3',
            name='LL',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Lessons Learned'),
        ),
    ]
