# Generated by Django 2.0.1 on 2018-05-09 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0071_auto_20180509_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 8, 24, 34, 715689)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 8, 24, 34, 715715)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 8, 24, 34, 715732)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 8, 24, 34, 715747)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 8, 24, 34, 715761)),
        ),
        migrations.AlterField(
            model_name='claimclassification',
            name='classification',
            field=models.CharField(max_length=25),
        ),
    ]
