# Generated by Django 2.0.1 on 2018-05-09 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0076_auto_20180509_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='penalty_periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_D3', models.DurationField(default='2 days')),
                ('duration_D4', models.DurationField(default='10 days')),
                ('duration_D5', models.DurationField(default='20 days')),
                ('duration_D6', models.DurationField(default='30 days')),
                ('duration_D8', models.DurationField(default='35 days')),
                ('delta', models.DurationField(default='7 days', verbose_name='time_between_supplier_updates')),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 45, 30, 197940)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 45, 30, 197963)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 45, 30, 197979)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 45, 30, 197993)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 45, 30, 198007)),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
    ]
