# Generated by Django 2.0.1 on 2018-05-23 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0084_auto_20180518_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=25)),
                ('subproject', models.CharField(max_length=25)),
                ('group', models.CharField(max_length=25)),
                ('task', models.CharField(max_length=75)),
                ('pilot', models.EmailField(max_length=25, verbose_name='(mail of) Pilot')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('original_due_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_date', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('importance', models.CharField(choices=[('LOW', 'low'), ('MID', 'mid'), ('HIGH', 'high'), ('IMP', 'Importance')], default='IMP', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 8, 7, 1, 51977)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 8, 7, 1, 52002)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 8, 7, 1, 52125)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 8, 7, 1, 52145)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 8, 7, 1, 52161)),
        ),
    ]
