# Generated by Django 2.0.1 on 2018-05-25 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0089_auto_20180524_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='W5_occurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W1', models.CharField(max_length=250)),
                ('W2', models.CharField(max_length=250)),
                ('W3', models.CharField(max_length=250)),
                ('W4', models.CharField(max_length=250)),
                ('W5', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 25, 29, 121910)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 25, 29, 121937)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 25, 29, 122066)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 25, 29, 122086)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 25, 29, 122102)),
        ),
        migrations.AddField(
            model_name='w5_occurance',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
