# Generated by Django 2.0.1 on 2018-05-25 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0090_auto_20180525_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='w5_occurance',
            old_name='W1',
            new_name='Why1',
        ),
        migrations.RenameField(
            model_name='w5_occurance',
            old_name='W2',
            new_name='Why2',
        ),
        migrations.RenameField(
            model_name='w5_occurance',
            old_name='W3',
            new_name='Why3',
        ),
        migrations.RenameField(
            model_name='w5_occurance',
            old_name='W4',
            new_name='Why4',
        ),
        migrations.RenameField(
            model_name='w5_occurance',
            old_name='W5',
            new_name='Why5',
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 44, 31, 263350)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 44, 31, 263387)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 44, 31, 263562)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 44, 31, 263598)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 13, 44, 31, 263614)),
        ),
    ]
