# Generated by Django 2.0.1 on 2018-05-25 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0091_auto_20180525_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='W5_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Why1', models.CharField(max_length=250)),
                ('Why2', models.CharField(max_length=250)),
                ('Why3', models.CharField(max_length=250)),
                ('Why4', models.CharField(max_length=250)),
                ('Why5', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 14, 40, 12, 871178)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 14, 40, 12, 871317)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 14, 40, 12, 871341)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 14, 40, 12, 871362)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 14, 40, 12, 871381)),
        ),
        migrations.AddField(
            model_name='w5_detection',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
