# Generated by Django 2.0.1 on 2018-05-28 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0092_auto_20180525_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='D4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause_occ', models.CharField(max_length=500)),
                ('root_cause_det', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='D4_reproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproduction_occ_pilot', models.CharField(blank=True, max_length=50, null=True)),
                ('reproduction_occ_date', models.DateField(blank=True, null=True)),
                ('defect_occ_reproduced', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('reproduction_det_pilot', models.CharField(blank=True, max_length=50, null=True)),
                ('reproduction_det_date', models.DateField(blank=True, null=True)),
                ('defect_det_reproduced', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 47, 39, 641654)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 47, 39, 641682)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 47, 39, 641699)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 47, 39, 641716)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 10, 47, 39, 641730)),
        ),
        migrations.AddField(
            model_name='d4_reproduction',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
        migrations.AddField(
            model_name='d4',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
