# Generated by Django 2.0.1 on 2018-05-28 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0093_auto_20180528_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='d4_reproduction',
            name='effective_det_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='d4_reproduction',
            name='effective_det_pilot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='d4_reproduction',
            name='effective_det_reproduced',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='d4_reproduction',
            name='effective_occ_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='d4_reproduction',
            name='effective_occ_pilot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pilot'),
        ),
        migrations.AddField(
            model_name='d4_reproduction',
            name='effective_occ_reproduced',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='action is effective!'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 13, 1, 42, 825136)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 13, 1, 42, 825162)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 13, 1, 42, 825179)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 13, 1, 42, 825194)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 13, 1, 42, 825208)),
        ),
        migrations.AlterField(
            model_name='d4',
            name='root_cause_det',
            field=models.CharField(max_length=500, verbose_name='root cause for non detection'),
        ),
        migrations.AlterField(
            model_name='d4',
            name='root_cause_occ',
            field=models.CharField(max_length=500, verbose_name='root cause for occurance'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='defect_occ_reproduced',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='occurance of defect reproduced?'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='reproduction_occ_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='reproduction_occ_pilot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pilot'),
        ),
    ]
