# Generated by Django 2.0.1 on 2018-05-28 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0094_auto_20180528_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=25)),
                ('subproject', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 33, 35, 186047)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 33, 35, 186073)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 33, 35, 186109)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 33, 35, 186131)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 33, 35, 186147)),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='defect_det_reproduced',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='non-detection of defect reproduced?'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='effective_det_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='effective_det_pilot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pilot'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='effective_det_reproduced',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='action is effective!'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='reproduction_det_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='reproduction_det_pilot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pilot'),
        ),
    ]
