# Generated by Django 2.0.1 on 2018-05-29 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0095_auto_20180528_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 14, 45, 21, 800967)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 14, 45, 21, 801017)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 14, 45, 21, 801054)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 14, 45, 21, 801085)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 14, 45, 21, 801116)),
        ),
        migrations.AlterField(
            model_name='task',
            name='pilot',
            field=models.EmailField(max_length=45, verbose_name='(mail of) Pilot'),
        ),
    ]
