# Generated by Django 2.0.6 on 2018-06-11 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0097_auto_20180604_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=25)),
                ('subproject', models.CharField(max_length=25)),
                ('task', models.IntegerField()),
                ('author', models.CharField(max_length=25)),
                ('comment', models.TextField(verbose_name='new comment')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('INTERNAL', 'internal'), ('ALL', 'all')], default='INTERNAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 7, 54, 19, 269979)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 7, 54, 19, 270013)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 7, 54, 19, 270043)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 7, 54, 19, 270066)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 7, 54, 19, 270086)),
        ),
    ]
