# Generated by Django 2.0.6 on 2018-06-18 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0098_auto_20180611_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='D7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DFMEA_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('DFMEA_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('DFMEA_date', models.DateField(blank=True, null=True)),
                ('DFMEA_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('PFMEA_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('PFMEA_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('PFMEA_date', models.DateField(blank=True, null=True)),
                ('PFMEA_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('LFMEA_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('LFMEA_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('LFMEA_date', models.DateField(blank=True, null=True)),
                ('LFMEA_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('controlplan_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('controlplan_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('controlplan_date', models.DateField(blank=True, null=True)),
                ('controlplan_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('WI_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('WI_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('WI_date', models.DateField(blank=True, null=True)),
                ('WI_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('MP_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('MP_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('MP_date', models.DateField(blank=True, null=True)),
                ('MP_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('Dstand_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Dstand_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('Dstand_date', models.DateField(blank=True, null=True)),
                ('Dstand_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('toolDstand_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('toolDstand_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('toolDstand_date', models.DateField(blank=True, null=True)),
                ('toolDstand_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('LLcard_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('LLcard_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('LLcard_date', models.DateField(blank=True, null=True)),
                ('LLcard_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('Gstand_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Gstand_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('Gstand_date', models.DateField(blank=True, null=True)),
                ('Gstand_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('Tstand_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Tstand_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('Tstand_date', models.DateField(blank=True, null=True)),
                ('Tstand_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('procedure_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('procedure_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('procedure_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('spec_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('spec_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('spec_date', models.DateField(blank=True, null=True)),
                ('spec_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('other_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('other_pilot', models.CharField(blank=True, max_length=25, null=True)),
                ('other_date', models.DateField(blank=True, null=True)),
                ('other_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 14, 46, 46, 606396)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 14, 46, 46, 606431)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 14, 46, 46, 606456)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 14, 46, 46, 606476)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 14, 46, 46, 606497)),
        ),
        migrations.AddField(
            model_name='d7',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
