# Generated by Django 2.0.6 on 2018-06-26 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0100_auto_20180619_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pilot_mail',
            field=models.EmailField(default='juergen.klotzek@nmb-minebea.com', max_length=45, verbose_name='(mail of) Pilot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 45, 2, 572530)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 45, 2, 572570)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 45, 2, 572596)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 45, 2, 572617)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 45, 2, 572644)),
        ),
        migrations.AlterField(
            model_name='task',
            name='pilot',
            field=models.ForeignKey(default=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.UserProfile'),
        ),
    ]
