# Generated by Django 2.0.6 on 2018-06-26 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0101_auto_20180626_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pilot_mail',
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 52, 59, 73)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 52, 59, 126)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 52, 59, 151)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 52, 59, 174)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 15, 52, 59, 201)),
        ),
    ]
