# Generated by Django 2.0.6 on 2018-06-26 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0102_auto_20180626_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 0, 12, 914048)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 0, 12, 914140)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 0, 12, 914201)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 0, 12, 914251)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 0, 12, 914312)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_comment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
