# Generated by Django 2.0.6 on 2018-06-27 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0104_auto_20180627_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('pilot',)},
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 8, 6, 56, 73642)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 8, 6, 56, 73703)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 8, 6, 56, 73746)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 8, 6, 56, 73801)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 8, 6, 56, 73846)),
        ),
    ]
