# Generated by Django 2.0.6 on 2018-06-27 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0105_auto_20180627_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('pilot__user',)},
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 9, 14, 41, 98132)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 9, 14, 41, 98196)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 9, 14, 41, 98243)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 9, 14, 41, 98303)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 9, 14, 41, 98351)),
        ),
    ]
