# Generated by Django 2.0.6 on 2018-07-16 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0109_auto_20180627_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='NMB_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 13, 51, 8, 24183)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 13, 51, 8, 24260)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 13, 51, 8, 24326)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 13, 51, 8, 24377)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 13, 51, 8, 24422)),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pilot',
            field=models.ForeignKey(default=15, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_of_task', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='function_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='mail_1',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='mail_2',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='mail_3',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
