# Generated by Django 2.0.6 on 2018-07-24 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0110_auto_20180716_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='can_be_viewed_by',
            field=models.ManyToManyField(related_name='_company_can_be_viewed_by_+', to='SMS.Company'),
        ),
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 10, 57, 18, 859670)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 10, 57, 18, 859738)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 10, 57, 18, 859794)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 10, 57, 18, 859846)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 10, 57, 18, 859898)),
        ),
    ]
