# Generated by Django 2.0.6 on 2018-07-31 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0111_auto_20180724_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('operator', models.CharField(max_length=25)),
                ('batch', models.CharField(max_length=25)),
                ('cavity', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='batch_1',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='batch_2',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='batch_3',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='cavity_1',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='cavity_2',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='cavity_3',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='operator_1',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='operator_2',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='operator_3',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='production_date_1',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='production_date_2',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='production_date_3',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='action_1',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='action_2',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='action_3',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='date_2',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='date_3',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='pilot_1',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='pilot_2',
        ),
        migrations.RemoveField(
            model_name='d3',
            name='pilot_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='function',
        ),
        migrations.RemoveField(
            model_name='team',
            name='function_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='function_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='function_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mail_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mail_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mail_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pilot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teammember_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teammember_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teammember_3',
        ),
        migrations.AddField(
            model_name='team',
            name='isPilot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='function',
            field=models.CharField(default='please edit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='please add', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 9, 14, 24, 21588)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 9, 14, 24, 21618)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 9, 14, 24, 21639)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 9, 14, 24, 21667)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 9, 14, 24, 21690)),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='effective_det_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth_name', to='SMS.UserProfile', verbose_name='pilot'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='effective_occ_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='some_other_special_name', to='SMS.UserProfile', verbose_name='pilot'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='reproduction_det_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_name', to='SMS.UserProfile', verbose_name='pilot'),
        ),
        migrations.AlterField(
            model_name='d4_reproduction',
            name='reproduction_occ_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='some_special_name', to='SMS.UserProfile', verbose_name='pilot'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='DFMEA_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='1+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='Dstand_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='7+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='Gstand_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='10+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='LFMEA_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='3+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='LLcard_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='9+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='MP_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='6+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='PFMEA_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='2+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='Tstand_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='11+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='WI_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='5+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='controlplan_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='4+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='other_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='14+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='procedure_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='12+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='spec_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='13+', to='SMS.UserProfile'),
        ),
        migrations.AlterField(
            model_name='d7',
            name='toolDstand_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='8+', to='SMS.UserProfile'),
        ),
        migrations.AddField(
            model_name='tracedata',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
    ]
