# Generated by Django 2.0.6 on 2018-08-06 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0112_auto_20180731_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='IQC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TASK', 'task'), ('INFO', 'info'), ('DEC', 'decision')], default='TASK', max_length=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 13, 21, 19, 733180)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 13, 21, 19, 733236)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 13, 21, 19, 733279)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 13, 21, 19, 733320)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 13, 21, 19, 733360)),
        ),
    ]
