# Generated by Django 2.0.6 on 2018-09-11 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0113_auto_20180806_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 12, 54, 25, 77060)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 12, 54, 25, 77133)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 12, 54, 25, 77204)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 12, 54, 25, 77263)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 12, 54, 25, 77317)),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_NOK_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_date_from',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_date_to',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_sorting_date',
            field=models.DateField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_NOK_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_date_from',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_date_to',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='FC_transit_sorting_date',
            field=models.DateField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_NOK_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_date_from',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_date_to',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_sorting_date',
            field=models.DateField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_NOK_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_date_from',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_date_to',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='NMB_transit_sorting_date',
            field=models.DateField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='fst_OK_parts_del_date',
            field=models.DateField(blank=True, null=True, verbose_name='delivery date NMB'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_NOK_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_date_from',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_date_to',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='sub_supplier_sorting_date',
            field=models.DateField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_NOK_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='NOK part production date'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_date_from',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='from prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_date_to',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='to prod. date sorted parts'),
        ),
        migrations.AlterField(
            model_name='d3',
            name='supplier_sorting_date',
            field=models.DateField(blank=True, null=True, verbose_name='sorting date'),
        ),
        migrations.AlterField(
            model_name='d4',
            name='root_cause_occ',
            field=models.CharField(max_length=500, verbose_name='root cause for occurence'),
        ),
    ]
