# Generated by Django 2.0.6 on 2018-09-12 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0114_auto_20180911_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='D6_effectiveness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_occ_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('effective_occ_reproduced', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='action is effective!')),
                ('effective_det_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('effective_det_reproduced', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='action is effective!')),
            ],
        ),
        migrations.RemoveField(
            model_name='d4_reproduction',
            name='effective_det_date',
        ),
        migrations.RemoveField(
            model_name='d4_reproduction',
            name='effective_det_pilot',
        ),
        migrations.RemoveField(
            model_name='d4_reproduction',
            name='effective_det_reproduced',
        ),
        migrations.RemoveField(
            model_name='d4_reproduction',
            name='effective_occ_date',
        ),
        migrations.RemoveField(
            model_name='d4_reproduction',
            name='effective_occ_pilot',
        ),
        migrations.RemoveField(
            model_name='d4_reproduction',
            name='effective_occ_reproduced',
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 12, 30, 33, 152025)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 12, 30, 33, 152097)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 12, 30, 33, 152220)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 12, 30, 33, 152279)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 12, 30, 33, 152334)),
        ),
        migrations.AddField(
            model_name='d6_effectiveness',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Claim'),
        ),
        migrations.AddField(
            model_name='d6_effectiveness',
            name='effective_det_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth_name', to='SMS.UserProfile', verbose_name='pilot'),
        ),
        migrations.AddField(
            model_name='d6_effectiveness',
            name='effective_occ_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='some_other_special_name', to='SMS.UserProfile', verbose_name='pilot'),
        ),
    ]
