# Generated by Django 2.0.6 on 2018-09-25 05:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0115_auto_20180912_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IATF16949_mandatory', models.BooleanField(default=True)),
                ('IATF16949_pic', models.FileField(blank=True, null=True, upload_to='')),
                ('IATF16949_cert_board', models.CharField(blank=True, max_length=200, null=True)),
                ('IATF16949_start', models.DateField(blank=True, null=True)),
                ('IATF16949_stop', models.DateField(blank=True, null=True)),
                ('IATF16949_validated', models.BooleanField(default=False)),
                ('IATF16949_rejected', models.BooleanField(default=False)),
                ('ISO9001_mandatory', models.BooleanField(default=False)),
                ('ISO9001_pic', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ISO9001_cert_board', models.CharField(blank=True, max_length=200, null=True)),
                ('ISO9001_start', models.DateField(blank=True, null=True)),
                ('ISO9001_stop', models.DateField(blank=True, null=True)),
                ('ISO9001_validated', models.BooleanField(default=False)),
                ('ISO9001_rejected', models.BooleanField(default=False)),
                ('ISO14001_mandatory', models.BooleanField(default=False)),
                ('ISO14001_pic', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ISO14001_cert_board', models.CharField(blank=True, max_length=200, null=True)),
                ('ISO14001_start', models.DateField(blank=True, null=True)),
                ('ISO14001_stop', models.DateField(blank=True, null=True)),
                ('ISO14001_validated', models.BooleanField(default=False)),
                ('ISO14001_rejected', models.BooleanField(default=False)),
                ('OHSAS18001_mandatory', models.BooleanField(default=False)),
                ('OHSAS18001_pic', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('OHSAS18001_cert_board', models.CharField(blank=True, max_length=200, null=True)),
                ('OHSAS18001_start', models.DateField(blank=True, null=True)),
                ('OHSAS18001_stop', models.DateField(blank=True, null=True)),
                ('OHSAS18001_validated', models.BooleanField(default=False)),
                ('OHSAS18001_rejected', models.BooleanField(default=False)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Company')),
            ],
        ),
        migrations.CreateModel(
            name='OtherCertifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('cert_board', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('stop', models.DateField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 7, 32, 29, 124740)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 7, 32, 29, 124816)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 7, 32, 29, 124873)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 7, 32, 29, 124926)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 7, 32, 29, 125024)),
        ),
    ]
