# Generated by Django 2.0.6 on 2018-10-11 00:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0116_auto_20180925_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('subproject', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Company')),
            ],
        ),
        migrations.AddField(
            model_name='d3',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D3',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 2, 6, 3, 398175)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D4',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 2, 6, 3, 398209)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D5',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 2, 6, 3, 398234)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D6',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 2, 6, 3, 398255)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='due_date_D8',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 2, 6, 3, 398275)),
        ),
        migrations.AlterField(
            model_name='othercertifications',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
